### ISSUE TITLE
May I update this?

### ISSUE THREAD

**Issue by ursi** [paulyoung/purescript-murmur3#5]
I'd like to make this package work with spago as well as change it to just wrap [this JS implementation](https://github.com/garycourt/murmurhash-js/blob/master/murmurhash3_gc.js) for (presumably) boosted performance. Would you be interested in a PR, adding me as a maintainer, or simply handing over the package namespace to me?

**Comment by paulyoung** [comment]
I'd accept PRs that update this to work with spago and the latest package set but I'd rather not turn this into a wrapper for a JS package.

**Comment by ursi** [comment]
Alright, I understand.
> I'd accept PRs that update this to work with spago and the latest package set

I don't have much of an interest in this package as it currently stands, as my application is performance critical.
